### ISSUE TITLE
conflict with diffuers‘ version?

### ISSUE THREAD

**Issue by jasoncow007** [glifxyz/ComfyUI-GlifNodes#2]
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 6, in <module>
    from diffusers import ConsistencyDecoderVAE
ImportError: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\__init__.py)

Cannot import D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'ConsistencyDecoderVAE' from 'diffusers' (D:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\__init__.py)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### ComfyUI Revision: 2088 [327ca131] | Released on '2024-03-27'
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\nodes.py", line 1888, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Marigold\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Marigold\nodes.py", line 5, in <module>
    from .marigold.model.marigold_pipeline import MarigoldPipeline
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
    from diffusers import (
ImportError: cannot import name 'LCMScheduler' from 'diffusers' (D:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\__init__.py)

Cannot import D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Marigold module for custom nodes: cannot import name 'LCMScheduler' from 'diffusers' (D:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers\__init__.py)

**Comment by alenknight** [comment]
I'm having this issue too and then import fails

**Comment by rvorias** [comment]
You also have this error: `ImportError: cannot import name 'LCMScheduler' from 'diffusers' (D:\ComfyUI-aki-v1.2\python\lib\site-packages\diffusers_init_.py)`. This leads me to suspect your diffusers version is not correct.
