### ISSUE TITLE
Does not affect the use, but there is an error

### ISSUE THREAD

**Issue by BoosterCore** [glifxyz/ComfyUI-GlifNodes#7]
```
[ERROR] An error occurred while retrieving information for the 'GlifmojiLoader' node.
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 434, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 355, in INPUT_TYPES
    for glifmoji in folder_paths.get_filename_list("glifmojis"):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 254, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 221, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'glifmojis'
```

**Comment by Amsmolfish** [comment]
I have the same error in linux, Start as normal, then as below. 

[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: /media/amsmol/ComfyUI/ComfyUI/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
[ERROR] An error occurred while retrieving information for the 'GlifmojiLoader' node.
Traceback (most recent call last):
  File "/media/amsmol/ComfyUI/ComfyUI/ComfyUI/server.py", line 434, in get_object_info
    out[x] = node_info(x)
  File "/media/amsmol/ComfyUI/ComfyUI/ComfyUI/server.py", line 412, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/media/amsmol/ComfyUI/ComfyUI/ComfyUI/custom_nodes/ComfyUI-GlifNodes/nodes.py", line 355, in INPUT_TYPES
    for glifmoji in folder_paths.get_filename_list("glifmojis"):
  File "/media/amsmol/ComfyUI/ComfyUI/ComfyUI/folder_paths.py", line 227, in get_filename_list
    out = get_filename_list_(folder_name)
  File "/media/amsmol/ComfyUI/ComfyUI/ComfyUI/folder_paths.py", line 194, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
KeyError: 'glifmojis'

**Comment by rvorias** [comment]
Removed that code since it got deprecated, thanks for reporting.
d776b6a3b8b82e56f99dc42f8b68d4f5cee825bd
